import React, { useEffect, useState } from "react";
import { Alert, Button, Card, CardBody, Col, Container, Form, FormGroup, Input, Label, Row } from "reactstrap";
import BreadCrumb from "../../shared/components/Common/BreadCrumb";
import DataTable, { Column } from "../components/DataTable";
import StatusBadge from "../components/StatusBadge";
import { ApiError, api, getPage } from "../api/client";
import { useAuth } from "../auth/AuthProvider";
import type { Collection, Muzaki, ZakatType } from "../api/types";

const CollectionsPage = () => {
  const { can } = useAuth();
  const [rows, setRows] = useState<Collection[]>([]); const [meta, setMeta] = useState<import("../api/client").PaginationMeta>();
  const [muzakis, setMuzakis] = useState<Muzaki[]>([]); const [types, setTypes] = useState<ZakatType[]>([]); const [error, setError] = useState<string | null>(null); const [page, setPage] = useState(1);
  const [form, setForm] = useState({ muzaki_id: "", zakat_type_id: "", expected_amount: "", due_date: "", reason: "" });
  const load = async () => { try { const result = await getPage<Collection>("/collections", { page }); setRows(result.data); setMeta(result.meta); } catch (e) { setError((e as ApiError).message); } };
  useEffect(() => { void load(); void Promise.all([getPage<Muzaki>("/muzakis", { per_page: 100 }).then((r) => setMuzakis(r.data)), getPage<ZakatType>("/zakat/types", { per_page: 100 }).then((r) => setTypes(r.data))]).catch((e) => setError((e as ApiError).message)); }, [page]);
  const create = async (event: React.FormEvent) => { event.preventDefault(); setError(null); try { await api.post("/collections", { ...form, source: "manual", currency: "IDR" }); setForm({ muzaki_id: "", zakat_type_id: "", expected_amount: "", due_date: "", reason: "" }); await load(); } catch (e) { setError((e as ApiError).message); } };
  const action = async (id: string, name: string) => { try { await api.post(`/collections/${id}/${name}`, name === "cancel" ? { reason: "Dibatalkan oleh amil" } : {}); await load(); } catch (e) { setError((e as ApiError).message); } };
  const columns: Column<Collection>[] = [{ header: "Collection", render: (row) => <><div className="fw-medium">{row.collection_number}</div><small className="text-muted">{row.source}</small></> }, { header: "Muzaki", render: (row) => row.muzaki?.display_name ?? row.muzaki_id }, { header: "Expected", render: (row) => `${row.expected_amount} ${row.currency}` }, { header: "Paid", render: (row) => row.paid_amount }, { header: "Remaining", render: (row) => row.remaining_amount }, { header: "Status", render: (row) => <StatusBadge status={row.status} /> }, { header: "Aksi", className: "text-end", render: (row) => row.status === "draft" && can("collection.confirm") ? <Button size="sm" color="primary" onClick={() => void action(row.id, "confirm")}>Konfirmasi</Button> : row.status === "expired" && can("collection.reactivate") ? <Button size="sm" color="warning" onClick={() => void action(row.id, "reactivate")}>Aktifkan</Button> : null }];
  return <div className="page-content"><Container fluid><BreadCrumb title="Collection" pageTitle="Penghimpunan" />{error ? <Alert color="danger">{error}</Alert> : null}<Card><CardBody>{can("collection.create_manual") ? <Form onSubmit={create} className="border rounded p-3 mb-4"><h5>Collection Manual</h5><Row><Col md={3}><FormGroup><Label>Muzaki</Label><Input type="select" required value={form.muzaki_id} onChange={(e) => setForm({ ...form, muzaki_id: e.target.value })}><option value="">Pilih muzaki</option>{muzakis.map((m) => <option key={m.id} value={m.id}>{m.display_name}</option>)}</Input></FormGroup></Col><Col md={3}><FormGroup><Label>Jenis Zakat</Label><Input type="select" required value={form.zakat_type_id} onChange={(e) => setForm({ ...form, zakat_type_id: e.target.value })}><option value="">Pilih jenis</option>{types.map((t) => <option key={t.id} value={t.id}>{t.name}</option>)}</Input></FormGroup></Col><Col md={2}><FormGroup><Label>Nominal</Label><Input required type="number" min="1" value={form.expected_amount} onChange={(e) => setForm({ ...form, expected_amount: e.target.value })} /></FormGroup></Col><Col md={2}><FormGroup><Label>Jatuh tempo</Label><Input type="date" value={form.due_date} onChange={(e) => setForm({ ...form, due_date: e.target.value })} /></FormGroup></Col><Col md={2} className="d-flex align-items-end"><Button color="success" type="submit">Buat</Button></Col></Row><Input placeholder="Alasan collection manual" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} /></Form> : null}<DataTable columns={columns} rows={rows} meta={meta} loading={false} onPageChange={setPage} rowKey={(row) => row.id} emptyMessage="Belum ada collection." /></CardBody></Card></Container></div>;
};

export default CollectionsPage;
