import React, { useEffect, useState } from "react";
import { Alert, Button, Card, CardBody, Col, Container, Form, FormGroup, Input, Label, Row } from "reactstrap";
import BreadCrumb from "../../shared/components/Common/BreadCrumb";
import DataTable, { Column } from "../components/DataTable";
import StatusBadge from "../components/StatusBadge";
import { ApiError, api, getPage } from "../api/client";
import { useAuth } from "../auth/AuthProvider";
import type { Program } from "../api/types";
const ProgramsPage = () => { const { can } = useAuth(); const [rows, setRows] = useState<Program[]>([]); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ name: "", program_type: "assistance", capacity_limit: "" }); const load = async () => { try { setRows((await getPage<Program>("/programs")).data); } catch (e) { setError((e as ApiError).message); } }; useEffect(() => { void load(); }, []); const create = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post("/programs", { ...form, capacity_limit: form.capacity_limit ? Number(form.capacity_limit) : undefined }); setForm({ name: "", program_type: "assistance", capacity_limit: "" }); await load(); } catch (e) { setError((e as ApiError).message); } }; const columns: Column<Program>[] = [{ header: "Program", render: (row) => <><div className="fw-medium">{row.program_code}</div><small className="text-muted">{row.name}</small></> }, { header: "Type", render: (row) => row.program_type }, { header: "Capacity", render: (row) => row.capacity_limit ?? "-" }, { header: "Status", render: (row) => <StatusBadge status={row.status} /> }]; return <div className="page-content"><Container fluid><BreadCrumb title="Program Management" pageTitle="Mustahik" />{error ? <Alert color="danger">{error}</Alert> : null}<Card><CardBody>{can("program.create") ? <Form onSubmit={create} className="border rounded p-3 mb-4"><h5>Buat Program</h5><Row><Col md={4}><FormGroup><Label>Nama</Label><Input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} /></FormGroup></Col><Col md={3}><FormGroup><Label>Type</Label><Input type="select" value={form.program_type} onChange={(e) => setForm({ ...form, program_type: e.target.value })}><option value="assistance">Assistance</option><option value="empowerment">Empowerment</option><option value="scholarship">Scholarship</option><option value="emergency">Emergency</option></Input></FormGroup></Col><Col md={3}><FormGroup><Label>Capacity</Label><Input type="number" min="1" value={form.capacity_limit} onChange={(e) => setForm({ ...form, capacity_limit: e.target.value })} /></FormGroup></Col><Col md={2} className="d-flex align-items-end"><Button color="success" type="submit">Simpan</Button></Col></Row></Form> : null}<DataTable columns={columns} rows={rows} loading={false} rowKey={(row) => row.id} emptyMessage="Belum ada program." /></CardBody></Card></Container></div>; }; export default ProgramsPage;
