<?php
namespace App\Services;
use App\Exceptions\ZakatException; use App\Models\BankAccount; use App\Models\BankStatement; use App\Models\BankTransaction; use App\Models\ReconciliationAdjustment; use App\Models\ReconciliationMatch; use App\Models\ReconciliationSession; use App\Models\ReconciliationTransaction; use Illuminate\Contracts\Pagination\LengthAwarePaginator; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\DB;
class BankReconciliationService
{
    public function __construct(private readonly AuditService $audit) {}
    public function accounts(array $f): LengthAwarePaginator { return BankAccount::query()->when($f['search']??null,fn($q,$v)=>$q->where(fn($x)=>$x->where('bank_name','ilike',"%{$v}%")->orWhere('account_name','ilike',"%{$v}%")->orWhere('account_code','ilike',"%{$v}%")))->latest()->paginate($f['per_page']??25); }
    public function createAccount(array $d): BankAccount { $d['account_number_masked']=BankAccount::mask($d['account_number']); $d['account_number_encrypted']=$d['account_number']; unset($d['account_number']); $a=BankAccount::create($d+['status'=>'ACTIVE']); $this->audit->record('bank_account_created',$a,context:['account_number_masked'=>$a->account_number_masked]); return $a; }
    public function account(string $id): BankAccount { return BankAccount::find($id)??throw ZakatException::notFound('Rekening bank tidak ditemukan.'); }
    public function import(BankAccount $account, UploadedFile $file, array $d): BankStatement { if(!in_array(strtolower($file->getClientOriginalExtension()),['csv','xlsx'],true)) throw ZakatException::conflict('File mutasi harus CSV atau XLSX.'); $rows=$this->rows($file); if(count($rows)<1) throw ZakatException::conflict('File mutasi tidak memiliki transaksi.'); return DB::transaction(function()use($account,$rows,$d,$file){ $statement=BankStatement::create(['bank_account_id'=>$account->id,'period_start'=>$d['period_start'],'period_end'=>$d['period_end'],'opening_balance'=>$d['opening_balance']??0,'closing_balance'=>$d['closing_balance']??0,'status'=>'IMPORTED','imported_by'=>auth()->id(),'imported_at'=>now()]); foreach($rows as $row){$date=$row[$d['date_column']??'transaction_date']??null; if(!$date)continue; $ref=(string)($row[$d['reference_column']??'reference']??'BTX'.now()->format('YmdHis').random_int(100,999)); $debit=(float)($row[$d['debit_column']??'debit']??0); $credit=(float)($row[$d['credit_column']??'credit']??0); $duplicate=BankTransaction::where('bank_account_id',$account->id)->whereDate('transaction_date',$date)->where(function($q)use($debit,$credit){$q->where('debit_amount',$debit)->where('credit_amount',$credit);})->exists(); $tx=BankTransaction::create(['bank_statement_id'=>$statement->id,'bank_account_id'=>$account->id,'transaction_reference'=>$ref,'transaction_date'=>$date,'description'=>$row[$d['description_column']??'description']??null,'debit_amount'=>$debit,'credit_amount'=>$credit,'balance'=>$row[$d['balance_column']??'balance']??null,'currency'=>$account->currency,'raw_data'=>$row,'duplicate_status'=>$duplicate?'POSSIBLE_DUPLICATE':'NEW']); if($duplicate)$this->audit->record('bank_transaction_duplicate_detected',$tx); } $statement->forceFill(['transaction_count'=>$statement->transactions()->count()])->saveQuietly(); $this->audit->record('bank_statement_imported',$statement,context:['filename'=>$file->getClientOriginalName()]); return $statement->load('transactions'); }); }
    public function transactions(array $f): LengthAwarePaginator { return BankTransaction::query()->when($f['status']??null,fn($q,$v)=>$q->where('match_status',$v))->when($f['bank_account_id']??null,fn($q,$v)=>$q->where('bank_account_id',$v))->latest('transaction_date')->paginate($f['per_page']??25); }
    public function sessions(array $f): LengthAwarePaginator { return ReconciliationSession::query()->latest()->paginate($f['per_page']??25); }
    public function createSession(array $d): ReconciliationSession { $s=ReconciliationSession::create($d+['status'=>'DRAFT','opening_balance'=>0,'closing_balance'=>0]); $this->audit->record('reconciliation_session_created',$s); return $s; }
    public function autoMatch(ReconciliationSession $s): ReconciliationSession { if(in_array($s->status,['CLOSED','COMPLETED'],true))throw ZakatException::invalidTransition('Sesi yang sudah selesai tidak dapat diubah.'); $count=0; $txs=BankTransaction::where('bank_account_id',$s->bank_account_id)->whereBetween('transaction_date',[$s->period_start,$s->period_end])->where('match_status','UNMATCHED')->get(); foreach($txs as $tx){$amount=bcadd((string)$tx->debit_amount,(string)$tx->credit_amount,2); $candidate=ReconciliationTransaction::where('transaction_reference',$tx->transaction_reference)->where('amount',$amount)->whereDate('transaction_date',$tx->transaction_date)->first(); if($candidate){ReconciliationMatch::create(['bank_transaction_id'=>$tx->id,'reconciliation_transaction_id'=>$candidate->id,'match_type'=>'AUTO','matched_amount'=>$amount,'confidence_score'=>100,'matched_by'=>auth()->id(),'matched_at'=>now(),'status'=>'MATCHED']);$tx->forceFill(['match_status'=>'MATCHED'])->saveQuietly();$count++;}} $s->forceFill(['status'=>'IN_PROGRESS'])->saveQuietly(); $this->audit->record('reconciliation_auto_match_completed',$s,context:['matched_count'=>$count]); return $this->refreshSummary($s); }
    public function match(BankTransaction $tx,array $d): BankTransaction { $internal=ReconciliationTransaction::find($d['reconciliation_transaction_id'])??throw ZakatException::notFound('Transaksi internal tidak ditemukan.'); $amount=(string)($d['matched_amount']??bcadd((string)$tx->debit_amount,(string)$tx->credit_amount,2)); $total=(string)$tx->matches()->sum('matched_amount'); if(bccomp(bcadd($total,$amount,2),bcadd((string)$tx->debit_amount,(string)$tx->credit_amount,2),2)>0)throw ZakatException::conflict('Nilai pencocokan melebihi nilai transaksi bank.'); $partial=bccomp(bcadd($total,$amount,2),bcadd((string)$tx->debit_amount,(string)$tx->credit_amount,2),2)<0; ReconciliationMatch::create(['bank_transaction_id'=>$tx->id,'reconciliation_transaction_id'=>$internal->id,'match_type'=>$partial?'PARTIAL':'MANUAL','matched_amount'=>$amount,'confidence_score'=>100,'matched_by'=>auth()->id(),'matched_at'=>now(),'status'=>'MATCHED']); $tx->forceFill(['match_status'=>$partial?'PARTIALLY_MATCHED':'MATCHED'])->saveQuietly(); $this->audit->record($partial?'bank_transaction_partial_matched':'bank_transaction_matched',$tx); return $tx->load('matches'); }
    public function exclude(BankTransaction $tx,string $reason):BankTransaction{$tx->forceFill(['match_status'=>'EXCLUDED'])->saveQuietly();$this->audit->record('bank_transaction_excluded',$tx,context:['reason'=>$reason]);return $tx;}
    public function complete(ReconciliationSession $s):ReconciliationSession{if($s->status==='CLOSED')throw ZakatException::invalidTransition('Sesi sudah ditutup.');$s=$this->refreshSummary($s);$s->forceFill(['status'=>'COMPLETED','completed_at'=>now()])->saveQuietly();$this->audit->record('reconciliation_completed',$s);return $s;}
    public function close(ReconciliationSession $s):ReconciliationSession{if($s->status!=='COMPLETED')throw ZakatException::invalidTransition('Sesi harus selesai sebelum ditutup.');$s->forceFill(['status'=>'CLOSED'])->saveQuietly();$this->audit->record('reconciliation_closed',$s);return $s;}
    private function refreshSummary(ReconciliationSession $s):ReconciliationSession{$q=BankTransaction::where('bank_account_id',$s->bank_account_id)->whereBetween('transaction_date',[$s->period_start,$s->period_end]);$credit=(string)$q->sum('credit_amount');$debit=(string)$q->sum('debit_amount');$matched=(string)BankTransaction::whereIn('match_status',['MATCHED','PARTIALLY_MATCHED'])->where('bank_account_id',$s->bank_account_id)->whereBetween('transaction_date',[$s->period_start,$s->period_end])->sum('credit_amount');$expected=bcsub(bcadd((string)$s->opening_balance,$credit,2),$debit,2);return tap($s->fresh(),fn($x)=>$x->forceFill(['matched_amount'=>$matched,'unmatched_amount'=>bcsub(bcadd($credit,$debit,2),$matched,2),'difference_amount'=>bcsub($expected,(string)$s->closing_balance,2)])->saveQuietly());}
    private function rows(UploadedFile $file):array{$ext=strtolower($file->getClientOriginalExtension()); if($ext==='csv'){ $h=null;$rows=[];$first=true;foreach(file($file->getRealPath(),FILE_IGNORE_NEW_LINES|FILE_SKIP_EMPTY_LINES)?:[] as $line){$r=str_getcsv($line);if($first){$h=array_map(fn($v)=>trim((string)$v),$r);$first=false;continue;}if($h!==null)$rows[]=array_combine($h,$r)?:[];}return $rows;} if(!class_exists('ZipArchive'))throw ZakatException::conflict('Server belum mendukung pembacaan XLSX.');$zip=new \ZipArchive();if($zip->open($file->getRealPath())!==true)throw ZakatException::conflict('File XLSX rusak.');$shared=[];if(($xml=$zip->getFromName('xl/sharedStrings.xml'))!==false){$s=simplexml_load_string($xml);foreach($s->si as $item)$shared[]=(string)($item->t??implode('',array_map('strval',$item->r->t??[])));}$sheet=simplexml_load_string((string)$zip->getFromName('xl/worksheets/sheet1.xml'));$rows=[];$header=[];foreach($sheet->sheetData->row as $row){$values=[];foreach($row->c as $cell){$value=(string)$cell->v;$type=(string)$cell['t'];if($type==='s')$value=$shared[(int)$value]??$value;$values[]=$value;}if($header===[])$header=array_map('trim',$values);else$rows[]=array_combine($header,$values)?:[];}$zip->close();return $rows;}
}
