<?php
namespace App\Services;
use App\Exceptions\ZakatException; use App\Models\Document; use App\Models\DocumentAccessLog; use App\Models\DocumentRelation; use App\Models\DocumentVerification; use App\Models\DocumentVersion; use Illuminate\Contracts\Pagination\LengthAwarePaginator; use Illuminate\Http\UploadedFile; use Illuminate\Support\Facades\DB; use Illuminate\Support\Facades\Storage; use Illuminate\Support\Str;
class DocumentService
{
    private const TYPES=['IDENTITY','FAMILY','ASSESSMENT','PROGRAM','PAYMENT','BANK','DISTRIBUTION','RECEIPT','REPORT','CONTRACT','LETTER','IMAGE','OTHER']; private const MIMES=['pdf','doc','docx','xls','xlsx','csv','jpg','jpeg','png','webp'];
    public function __construct(private readonly AuditService $audit){}
    public function list(array $f):LengthAwarePaginator{return Document::query()->when($f['search']??null,fn($q,$v)=>$q->where('document_name','ilike',"%{$v}%")->orWhere('document_number','ilike',"%{$v}%"))->when($f['status']??null,fn($q,$v)=>$q->where('status',$v))->when($f['document_type']??null,fn($q,$v)=>$q->where('document_type',$v))->latest()->paginate($f['per_page']??25);}
    public function find(string $id):Document{return Document::with(['relations','versions','verifications'])->find($id)??throw ZakatException::notFound('Dokumen tidak ditemukan.');}
    public function upload(UploadedFile $file,array $d):Document{$ext=strtolower($file->getClientOriginalExtension());if(!in_array($ext,self::MIMES,true))throw ZakatException::conflict('Jenis file belum didukung.');if($file->getSize()>10*1024*1024)throw ZakatException::conflict('Ukuran file maksimal 10 MB.');$mime=$file->getMimeType()?:'application/octet-stream';$checksum=hash_file('sha256',$file->getRealPath());$duplicate=Document::where('checksum',$checksum)->first();$doc=DB::transaction(function()use($file,$d,$ext,$mime,$checksum){$doc=Document::create(['document_name'=>$d['document_name'],'original_filename'=>$file->getClientOriginalName(),'stored_filename'=>Str::ulid().'.'.$ext,'document_type'=>$d['document_type'],'category'=>$d['category']??null,'mime_type'=>$mime,'extension'=>$ext,'file_size'=>$file->getSize(),'storage_disk'=>'private','storage_path'=>'documents/'.(now()->format('Y/m')).'/'.Str::ulid(),'checksum'=>$checksum,'visibility'=>$d['visibility']??'PRIVATE','status'=>$d['status']??'ACTIVE','expires_at'=>$d['expires_at']??null,'uploaded_by'=>auth()->id()]);$path=Storage::disk('private')->putFileAs(dirname($doc->storage_path),$file,basename($doc->storage_path).'.'.$ext);$doc->forceFill(['storage_path'=>$path])->saveQuietly();$this->audit->record('document_uploaded',$doc);return $doc;});if($duplicate)$this->audit->record('document_duplicate_detected',$doc,context:['existing_document_id'=>$duplicate->id]);return $doc;}
    public function update(Document $doc,array $d):Document{if($doc->status==='ARCHIVED')throw ZakatException::invalidTransition('Dokumen arsip bersifat hanya-baca.');$doc->fill($d);$doc->save();$this->audit->record('document_updated',$doc);return $doc;}
    public function delete(Document $doc):Document{$doc->forceFill(['status'=>'DELETED'])->saveQuietly();$doc->delete();$this->audit->record('document_deleted',$doc);return $doc;}
    public function restore(Document $doc):Document{$doc->restore();$doc->forceFill(['status'=>'ACTIVE'])->saveQuietly();$this->audit->record('document_restored',$doc);return $doc;}
    public function replace(Document $doc,UploadedFile $file,array $d):Document{$this->assertFile($file);$old=$doc->storage_path;$ext=strtolower($file->getClientOriginalExtension());$newPath=Storage::disk('private')->putFile('documents/'.now()->format('Y/m'),$file);$version=(int)$doc->version+1;DocumentVersion::create(['document_id'=>$doc->id,'version_number'=>$version,'storage_path'=>$newPath,'file_size'=>$file->getSize(),'checksum'=>hash_file('sha256',$file->getRealPath()),'change_note'=>$d['change_note']??null,'created_by'=>auth()->id()]);$doc->forceFill(['storage_path'=>$newPath,'stored_filename'=>basename($newPath),'file_size'=>$file->getSize(),'checksum'=>hash_file('sha256',$file->getRealPath()),'version'=>$version,'original_filename'=>$file->getClientOriginalName(),'extension'=>$ext,'mime_type'=>$file->getMimeType()])->saveQuietly();Storage::disk('private')->delete($old);$this->audit->record('document_replaced',$doc);return $doc;}
    public function verify(Document $doc,bool $ok,?string $note):Document{$doc->forceFill(['status'=>$ok?'VERIFIED':'REJECTED'])->saveQuietly();DocumentVerification::create(['document_id'=>$doc->id,'status'=>$ok?'VERIFIED':'REJECTED','verification_note'=>$note,'verified_by'=>auth()->id(),'verified_at'=>now()]);$this->audit->record($ok?'document_verified':'document_rejected',$doc);return $doc;}
    public function relate(Document $doc,array $d):DocumentRelation{return tap(DocumentRelation::create($d+['document_id'=>$doc->id,'created_by'=>auth()->id()]),fn($r)=>$this->audit->record('document_relation_created',$doc,context:['relation_id'=>$r->id]));}
    public function removeRelation(Document $doc, string $relationId): void { $relation=$doc->relations()->find($relationId)??throw ZakatException::notFound('Relasi dokumen tidak ditemukan.'); $relation->delete(); $this->audit->record('document_relation_deleted',$doc,context:['relation_id'=>$relationId]); }
    public function archive(Document $doc): Document { if($doc->status==='DELETED') throw ZakatException::invalidTransition('Dokumen yang dihapus tidak dapat diarsipkan.'); $doc->forceFill(['status'=>'ARCHIVED'])->saveQuietly(); $this->audit->record('document_archived',$doc); return $doc; }
    public function log(Document $doc,string $action):void{DocumentAccessLog::create(['document_id'=>$doc->id,'user_id'=>auth()->id(),'action'=>$action,'ip_address'=>request()->ip(),'user_agent'=>request()->userAgent(),'accessed_at'=>now(),'created_at'=>now()]);$this->audit->record('document_'.$action,$doc);}
    public function assertFile(UploadedFile $file):void{if(!$file->isValid()||$file->getSize()>10*1024*1024)throw ZakatException::conflict('File tidak valid atau melebihi 10 MB.');}
}
