import React, { useEffect, useState } from "react";
import { Alert, Button, Card, CardBody, Col, Container, Form, FormGroup, Input, Label, Row } from "reactstrap";
import BreadCrumb from "../../shared/components/Common/BreadCrumb";
import DataTable, { Column } from "../components/DataTable";
import StatusBadge from "../components/StatusBadge";
import { ApiError, api, getPage } from "../api/client";
import { useAuth } from "../auth/AuthProvider";
import type { Mustahik } from "../api/types";
const MustahiksPage = () => { const { can } = useAuth(); const [rows, setRows] = useState<Mustahik[]>([]); const [meta, setMeta] = useState<import("../api/client").PaginationMeta>(); const [error, setError] = useState<string | null>(null); const [page, setPage] = useState(1); const [form, setForm] = useState({ full_name: "", phone: "", identity_type: "nik", identity_number: "" }); const load = async () => { try { const result = await getPage<Mustahik>("/mustahiks", { page }); setRows(result.data); setMeta(result.meta); } catch (e) { setError((e as ApiError).message); } }; useEffect(() => { void load(); }, [page]); const create = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post("/mustahiks", form); setForm({ full_name: "", phone: "", identity_type: "nik", identity_number: "" }); await load(); } catch (e) { setError((e as ApiError).message); } }; const columns: Column<Mustahik>[] = [{ header: "Mustahik", render: (row) => <><div className="fw-medium">{row.display_name}</div><small className="text-muted">{row.mustahik_number}</small></> }, { header: "Type", render: (row) => row.mustahik_type }, { header: "Phone", render: (row) => row.phone ?? "-" }, { header: "Verification", render: (row) => <StatusBadge status={row.verification_status} /> }, { header: "Eligibility", render: (row) => <StatusBadge status={row.eligibility_status} /> }, { header: "Status", render: (row) => <StatusBadge status={row.status} /> }]; return <div className="page-content"><Container fluid><BreadCrumb title="Mustahik" pageTitle="Beneficiary" />{error ? <Alert color="danger">{error}</Alert> : null}<Card><CardBody>{can("mustahik.create") ? <Form onSubmit={create} className="border rounded p-3 mb-4"><h5>Daftar Mustahik</h5><Row><Col md={4}><FormGroup><Label>Nama lengkap</Label><Input required value={form.full_name} onChange={(e) => setForm({ ...form, full_name: e.target.value })} /></FormGroup></Col><Col md={2}><FormGroup><Label>Telepon</Label><Input value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /></FormGroup></Col><Col md={2}><FormGroup><Label>Jenis identitas</Label><Input type="select" value={form.identity_type} onChange={(e) => setForm({ ...form, identity_type: e.target.value })}><option value="nik">NIK</option><option value="passport">Passport</option><option value="other">Lainnya</option></Input></FormGroup></Col><Col md={2}><FormGroup><Label>Nomor identitas</Label><Input value={form.identity_number} onChange={(e) => setForm({ ...form, identity_number: e.target.value })} /></FormGroup></Col><Col md={2} className="d-flex align-items-end"><Button color="success" type="submit">Daftar</Button></Col></Row></Form> : null}<DataTable columns={columns} rows={rows} meta={meta} loading={false} onPageChange={setPage} rowKey={(row) => row.id} emptyMessage="Belum ada mustahik." /></CardBody></Card></Container></div>; }; export default MustahiksPage;
