import React, { useEffect, useState } from "react";
import { Alert, Button, Card, CardBody, Col, Container, Form, FormGroup, Input, Label, Row } from "reactstrap";
import BreadCrumb from "../../shared/components/Common/BreadCrumb";
import DataTable, { Column } from "../components/DataTable";
import StatusBadge from "../components/StatusBadge";
import { ApiError, api, getPage } from "../api/client";
import { useAuth } from "../auth/AuthProvider";
import type { Distribution } from "../api/types";
const DistributionsPage = () => { const { can } = useAuth(); const [rows, setRows] = useState<Distribution[]>([]); const [error, setError] = useState<string | null>(null); const [form, setForm] = useState({ mustahik_id: "", fund_id: "", distribution_type: "cash", requested_amount: "", description: "" }); const load = async () => { try { setRows((await getPage<Distribution>("/distributions")).data); } catch (e) { setError((e as ApiError).message); } }; useEffect(() => { void load(); }, []); const create = async (event: React.FormEvent) => { event.preventDefault(); try { await api.post("/distributions", { ...form, requested_amount: Number(form.requested_amount) }); setForm({ mustahik_id: "", fund_id: "", distribution_type: "cash", requested_amount: "", description: "" }); await load(); } catch (e) { setError((e as ApiError).message); } }; const columns: Column<Distribution>[] = [{ header: "Distribution", render: (row) => <><div className="fw-medium">{row.distribution_number}</div><small className="text-muted">{row.mustahik?.display_name ?? row.mustahik_id}</small></> }, { header: "Type", render: (row) => `${row.source_type} · ${row.distribution_type}` }, { header: "Requested", render: (row) => row.requested_amount }, { header: "Distributed", render: (row) => row.distributed_amount }, { header: "Status", render: (row) => <StatusBadge status={row.status} /> }]; return <div className="page-content"><Container fluid><BreadCrumb title="Distribution" pageTitle="Program" />{error ? <Alert color="danger">{error}</Alert> : null}<Card><CardBody>{can("distribution.create") ? <Form onSubmit={create} className="border rounded p-3 mb-4"><h5>Buat Distribution</h5><Row><Col md={3}><FormGroup><Label>ID Mustahik</Label><Input required value={form.mustahik_id} onChange={(e) => setForm({ ...form, mustahik_id: e.target.value })} /></FormGroup></Col><Col md={3}><FormGroup><Label>ID Fund</Label><Input required value={form.fund_id} onChange={(e) => setForm({ ...form, fund_id: e.target.value })} /></FormGroup></Col><Col md={2}><FormGroup><Label>Type</Label><Input type="select" value={form.distribution_type} onChange={(e) => setForm({ ...form, distribution_type: e.target.value })}><option value="cash">Cash</option><option value="bank_transfer">Bank Transfer</option><option value="goods">Goods</option><option value="service">Service</option></Input></FormGroup></Col><Col md={2}><FormGroup><Label>Nominal</Label><Input required type="number" min="1" value={form.requested_amount} onChange={(e) => setForm({ ...form, requested_amount: e.target.value })} /></FormGroup></Col><Col md={2} className="d-flex align-items-end"><Button color="success" type="submit">Simpan</Button></Col></Row></Form> : null}<DataTable columns={columns} rows={rows} loading={false} rowKey={(row) => row.id} emptyMessage="Belum ada distribution." /></CardBody></Card></Container></div>; }; export default DistributionsPage;
